export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOAD_ERROR = "LOAD_ERROR";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_ABOUT_ME = "UPDATE_ABOUT_ME";
export const UPDATE_SOCIALS = "UPDATE_SOCIALS";
export const UPDATE_PROFESSIONAL_INFO = "UPDATE_PROFESSIONAL_INFO";
export const UPDATE_INTERESTS = "UPDATE_INTERESTS";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const FOLLOW = "FOLLOW";
export const UNFOLLOW = "UNFOLLOW";
